### ISSUE TITLE
Incorrect values of 'WT_name' column in the dataset file

### ISSUE THREAD

**Issue by Stephen2526** [Rocklin-Lab/cdna-display-proteolysis-pipeline#3]
Hello,

Impressive works for the community!

According to the description of columns in 'K50_dG_Dataset1_Dataset2.csv' (Table S4), 'WT_name' column should have values for wild-type domain names. But in the real csv file, this column stores pdb names instead of domain names. (e.g. 2B88.pdb_pross1). And there is no description of what domain classification system was used in the study, Pfam, InterPro, SUPFAM or others?

Thanks

**Comment by grocklin** [comment]
These names simply link each mutant back to our own name for the WT- they aren't tied to any external domain classification system.
